# Generated by Django 4.2.6 on 2024-01-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0002_remove_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
