# Generated by Django 4.2.6 on 2024-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0006_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
