# Generated by Django 4.2.6 on 2024-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0007_case_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='culprit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='describe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='victim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
