# Generated by Django 4.2.6 on 2024-02-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0008_alter_case_culprit_alter_case_describe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='culprit',
        ),
    ]
