# Generated by Django 4.2.9 on 2024-02-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0009_remove_case_culprit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='describe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
